os: osx
osx_image: xcode12.2
addons:
  homebrew:
    update: true
    packages:
    - shellcheck
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup

language: sh

script:
  - shellcheck laptop.local
  - sh laptop.local

notifications:
  email: false

branches:
  only:
    - master
