name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  schedule:
    # Schedule the job to run at 9am on Tuesday.
    - cron: "0 9 * * 2"

jobs:
  build:
    strategy:
      matrix:
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
        # https://github.blog/changelog/2026-07-16-xcode-27-runner-image-now-in-public-preview/#a-new-support-model-for-macos-images
        # https://github.blog/changelog/2026-09-10-xcode-27-runner-image-now-runs-on-macos-27/
        # https://github.com/actions/runner-images/blob/main/images/macos/xcode-27-arm64-Readme.md
        os:
          - macos-26
          - xcode-27
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck mac
      - run: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=true sh mac
